//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Engine.Net {

public enum EChannel : ulong {
  R = 0UL,
  G = 1UL,
  B = 2UL,
  A = 3UL,
  D = 4UL,
  S = 5UL,
  BC = 6UL,
  E = 7UL,
  ETC = 8UL
}

}
