//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Engine.Net {

public enum EChannelType : ulong {
  UNorm = 0UL,
  SNorm = 1UL,
  UInt = 2UL,
  SInt = 3UL,
  Float = 4UL,
  UNorm_SRGB = 5UL,
  Typeless = 6UL,
  SharedExp = 7UL
}

}
