//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Engine.Net {

public class SampleDesc : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SampleDesc(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SampleDesc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SampleDesc() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IFormatPINVOKE.delete_SampleDesc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint Count {
    set {
      IFormatPINVOKE.SampleDesc_Count_set(swigCPtr, value);
    } 
    get {
      uint ret = IFormatPINVOKE.SampleDesc_Count_get(swigCPtr);
      return ret;
    } 
  }

  public uint Quality {
    set {
      IFormatPINVOKE.SampleDesc_Quality_set(swigCPtr, value);
    } 
    get {
      uint ret = IFormatPINVOKE.SampleDesc_Quality_get(swigCPtr);
      return ret;
    } 
  }

  public SampleDesc() : this(IFormatPINVOKE.new_SampleDesc__SWIG_0(), true) {
  }

  public SampleDesc(uint count, uint quality) : this(IFormatPINVOKE.new_SampleDesc__SWIG_1(count, quality), true) {
  }

}

}
