#include "RayTracingPipelineState.h"
#include "D3D12RayTracing.h"

using namespace platform_ex::Windows::D3D12;

RayTracingPipelineState::RayTracingPipelineState(const platform::Render::RayTracingPipelineStateInitializer& initializer)
{
	//D3D12_STATE_SUBOBJECT_TYPE_NODE_MASK

	//D3D12_STATE_SUBOBJECT_TYPE_GLOBAL_ROOT_SIGNATURE

	//D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_PIPELINE_CONFIG

	//D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_SHADER_CONFIG

	//ShaderIdentifier
	//D3D12_STATE_SUBOBJECT_TYPE_DXIL_LIBRARY -RayGen
	//D3D12_STATE_SUBOBJECT_TYPE_DXIL_LIBRARY -HitGroup
	//D3D12_STATE_SUBOBJECT_TYPE_DXIL_LIBRARY -Miss

	//D3D12_STATE_SUBOBJECT_TYPE_HIT_GROUP

	//D3D12_STATE_SUBOBJECT_TYPE_LOCAL_ROOT_SIGNATURE
}
